### ISSUE TITLE
Rewrite Dataloader class

### ISSUE THREAD

**Issue by s1Sharp** [s1Sharp/cnn#5]
Разделите класс dataloader, чтобы была возможность создавать разные сущности для тренировочных и тестовых данных:

1) поменяйте конструктор на что-то вроде 
### public Dataloader(**bool train=true**, bool shuffle = false)
2) Скачивайте необходимые данные в зависимости от заданной переменной train=<true/false>
3) Определите функции перезагрузки данный, проверки на валидность и получения batch`a данных

**Comment by purritt** [comment]
[https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5UmIlzwQKkbTQD5iss7h9-2PGdNYqP8CQ3_XfXHxs6g&s](url)
